### ISSUE TITLE
To make it work in Anki 23.10 and higher, just change exec_ to exec

### ISSUE THREAD

**Issue by nclvrps** [glfharris/symbols#5]
The add-on numbered 1461102936 stopped working when Anki updated to version 23.10. The solution is simply to changed `exec_` to `exec` in line 36 of the symbols.py in the add-on, or on line 44 of Symbols.py of the repository here (they are not in sync). This reflects a change in Qt itself. It should still work in older versions of Anki.

**Comment by glfharris** [comment]
Cheers! Got to be honest, I sort of forgot about this and I've been using a different add-on until thats also broke. Have update this one and pushed it to Ankiweb.

Thanks again!
